### ISSUE TITLE
Server & Mobil App Theme Color Integration

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/ios#166]
@marinofaggiana , Is it possible to integrate the application with the Nextcloud application [Theming](https://github.com/nextcloud/server/tree/master/apps/theming)?

![navcolor](https://cloud.githubusercontent.com/assets/297968/24629340/5e0eb0a2-18c1-11e7-943a-0e3b21112764.png)

**Comment by rakekniven** [comment]
Are you sure to use the default colors of nextcloud. AFAIK they are the same und your screenshot from web UI differs.

**Comment by emresaracoglu** [comment]
Hi @rakekniven, Yes I do not use default color, I'm talking about that too.. We can change colors on the server editon and It may be better to see the same color in the mobile interface.

**Comment by rakekniven** [comment]
So you talk about transferring server branding information to the iOS client and adapting it?

**Comment by emresaracoglu** [comment]
Absolutely!
What do you think @marinofaggiana ?

**Comment by marinofaggiana** [comment]
@jancborchardt this is for you :-)

**Comment by jancborchardt** [comment]
@marinofaggiana I think it would be cool if the apps header would have the color of the account/instance as themed.

However, is it possible on iOS to dynamically change that?

cc @TobiasKaminsky @AndyScherzinger @mario and @nextcloud/theming for info

**Comment by MariusBluem** [comment]
A general theme color change in an app is possible through iOS (example YouVersion Bible App):

**Comment by marinofaggiana** [comment]
Do you Like ?

https://cloud.twsweb.it/index.php/s/0LHvnNIWqOZQPzs

**Comment by MorrisJobke** [comment]
> Do you Like guys ?
> 
> https://cloud.twsweb.it/index.php/s/0LHvnNIWqOZQPzs

Looks already really nice. We only have the problem, that the folder icons in the browser are as well themed and in the app now look a bit out of place. :/

cc @nextcloud/designers

**Comment by emresaracoglu** [comment]
I applaud you 👏  Marino but I guess you have probably seen this little detail; icons

**Comment by MorrisJobke** [comment]
> Also, is not it possible for the "More" tab to change color? @marinofaggiana

Maybe it's best to just use the color in the "More" tab instead of the background image for now.

**Comment by enoch85** [comment]
Really cool stuff! Would this be possible in the Android Client as well @tobiasKaminsky?

**Comment by marinofaggiana** [comment]
Guys folder icon etc. are detail and @MorrisJobke I can use the image of Login Image for menu "More" @jancborchardt ...

https://cloud.twsweb.it/index.php/s/E2MXtDYdiKFnUJK

With color .... see only Documents folder, this is only a "experiment" if you like it .... I continue for next version.

**Comment by MorrisJobke** [comment]
> Guys folder icon etc. are detail and @MorrisJobke I can use the image of Login Image for menu "More" @jancborchardt ...

😱 This looks really nice 👍

**Comment by AndyScherzinger** [comment]
This can also be done to some extend on Android, but is way more work than people expect it to be. To do it right like you already realized, we need to dynamically do this on Android for Action bar, buttons, edit texts, check boxes, icons, any kind of color themed UI element. The icons are PNG files so we need to tint them on the fly and cache them per user :/
So it really depends on how far we have to go here...

**Comment by mario** [comment]
We also need to decide when these options take priority over hard-coded branding options:

a) in regular client
b) in branded client
c) in both

**Comment by emresaracoglu** [comment]
> Maybe it's best to just use the color in the "More" tab instead of the background image for now.

I agree with you 👍 

> We also need to decide when these options take priority over hard-coded branding options:
> 
> a) in regular client
> b) in branded client
> c) in both

Of course "C" option. Can be found in both.

**Comment by marinofaggiana** [comment]
@mario I have create a k_option_use_themingColor (YES/NO)

**Comment by marinofaggiana** [comment]
ok guys.

https://cloud.twsweb.it/index.php/s/yEWWHchOmZ70uRM

done.

**Comment by emresaracoglu** [comment]
I'm waiting for the version with excitement @marinofaggiana

**Comment by mario** [comment]
Looks nice, but some icons are still not the chosen color :P

**Comment by marinofaggiana** [comment]
He he for test version

**Comment by marinofaggiana** [comment]
https://cloud.twsweb.it/index.php/s/kJJk1nsAPBmvWi8

@jancborchardt last question the central tab bar button (+) ... style color Nextcloud ??

**Comment by juliushaertl** [comment]
@marinofaggiana That looks really great. :clap: 

Is it possible to also use the logo from the theming app inside the header bar of the iOS app? Or we should maybe just add "Files" as a title instead of the Nextcloud logo to be consistent with the other tabs?

Do you make sure that text is still readable when for example choosing a very bright color in the theming app?

**Comment by emresaracoglu** [comment]
> Is it possible to also use the logo from the theming app inside the header bar of the iOS app? Or we should maybe just add "Files" as a title instead of the Nextcloud logo to be consistent with the other tabs?

That idea is nice too!

> Do you make sure that text is still readable when for example choosing a very bright color in the theming app?

Can not be sure. Because no background color options, therefore I think nobody will make a brilliant color choice but maybe [this link](http://stackoverflow.com/questions/2509443/check-if-uicolor-is-dark-or-bright) can help for colors

**Comment by juliushaertl** [comment]
>Can not be sure. Because no background color options, therefore I think
>nobody will make a brilliant color choice but maybe [this
>link](http://stackoverflow.com/questions/2509443/check-if-uicolor-is-dark-or-bright)
>can help for colors

We already use calculations like those in the theming app, see https://github.com/nextcloud/server/blob/master/apps/theming/lib/Util.php#L59 for implementation details.

**Comment by jancborchardt** [comment]
@mario regarding if branding or theming takes precendence: I would say if someone changes the theme, then it's good the client changes too.

If we want to prevent it for a specific branded client then we could just add some sort of override switch?

**Comment by emresaracoglu** [comment]
I tested now. It's been a great work! @marinofaggiana

**Comment by rakekniven** [comment]
Cheers @marinofaggiana 

Really great work.
My cloud used very dark colors. Now my phone looks like gothic.

Closing issue?

**Comment by marinofaggiana** [comment]
Yes @rakekniven  thanks to everybody for your work

**Comment by jancborchardt** [comment]
Awesome work @marinofaggiana! :)

Thanks for testing @rakekniven @emresaracoglu @juliushaertl @MariusBluem! :)

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky I searched for a solution for Android but Android doesn't support such a feature out of the box, we can dynamically switch static themes shipped with the app and we are able to programmatically change (some) colorings at runtime but we can't simple "replace" nextcloud-blue is a centralized way :(

**Comment by dartcafe** [comment]
Just installed 2.17.2 and the changes are working great. Thanks for this impromement. But maybe there is one issue remaining. I have an installation with a light color (#FFFD48) and in the web app, the text color changes to a dark version automacilally. In the iOS app the colors stay white, wich results in poor contrast. Is it possible to adopt the font color too?

Some of the bottom buttons in the iOS app stay in default color, and some (files ans the plus sign) adopt the background color. I think it would be better to keep them in the default color, because yellow on white (in my case) is difficult to identify too.

**Comment by jancborchardt** [comment]
cc @marinofaggiana @juliushaertl on that :)

**Comment by tobiasKaminsky** [comment]
We now have two PRs on android
Branding (means hardcoded values): https://github.com/nextcloud/android/pull/1030
Theming (dynamic changes with theming app): https://github.com/nextcloud/android/pull/1031

**Comment by juliushaertl** [comment]
@marinofaggiana @tobiasKaminsky 

For the case of checking whether it is a dark or light color we use the following function on the server: 
https://github.com/nextcloud/server/blob/master/apps/theming/lib/Util.php#L90-L102 Sould be easy to adopt on iOS/Android. If it is greater than 0.5 you can use black as a foreground color otherwise you can use white.
