### ISSUE TITLE
Crash in 4.2.1 on iPad Air 4th Gen

### ISSUE THREAD

**Issue by markshep** [nextcloud/ios#1886]
### Steps to reproduce

1. Run Nextcloud on my wife's iPad
2. Watch it disappear within a few seconds of opening without having completed any of the pending uploads

### Expected behaviour

It doesn't crash.

### Actual behaviour

It crashes.

### Screenshots

N/A

### Logs

```
Incident Identifier: 6B901A87-E243-4F33-AEED-6F19F8A001DD
CrashReporter Key:   173c8aeb41a874754818897ff65cddcde30638b0
Hardware Model:      iPad13,1
Process:             Nextcloud [395]
Path:                /private/var/containers/Bundle/Application/7E0CAE0A-5A69-4DE5-A91E-3003CDA407A9/Nextcloud.app/Nextcloud
Identifier:          it.twsweb.Nextcloud
Version:             4.2.1 (7)
AppStoreTools:       13C90b
AppVariant:          1:iPad13,1:15
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           it.twsweb.Nextcloud [541]

Date/Time:           2022-02-12 20:20:36.0375 +0000
Launch Time:         2022-02-12 20:20:30.1345 +0000
OS Version:          iPhone OS 15.3.1 (19D52)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x0000000104db0e6c
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL; [5]
Terminating Process: exc handler [395]

Terminating Process: exc handler [395]
Triggered by Thread:  0

Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   Nextcloud                     	       0x104db0e6c 0x104cf0000 + 790124
1   Nextcloud                     	       0x104db0db0 0x104cf0000 + 789936
2   Nextcloud                     	       0x104dcd5b0 0x104cf0000 + 906672
3   Nextcloud                     	       0x1054d7410 0x104cf0000 + 8287248
4   Nextcloud                     	       0x1054d9ce4 0x104cf0000 + 8297700
5   Nextcloud                     	       0x1054722dc 0x104cf0000 + 7873244
6   libdispatch.dylib             	       0x182e9a924 _dispatch_call_block_and_release + 32
7   libdispatch.dylib             	       0x182e9c670 _dispatch_client_callout + 20
8   libdispatch.dylib             	       0x182eaab70 _dispatch_main_queue_callback_4CF + 944
9   CoreFoundation                	       0x1831e2d84 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
10  CoreFoundation                	       0x18319cf5c __CFRunLoopRun + 2540
11  CoreFoundation                	       0x1831b0468 CFRunLoopRunSpecific + 600
12  GraphicsServices              	       0x19ed5438c GSEventRunModal + 164
13  UIKitCore                     	       0x185b535d0 -[UIApplication _run] + 1100
14  UIKitCore                     	       0x1858d1f74 UIApplicationMain + 364
15  Nextcloud                     	       0x104d22a3c 0x104cf0000 + 207420
16  dyld                          	       0x105e79aa4 start + 520

Thread 1:
0   libsystem_pthread.dylib       	       0x1f2a9ae8c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1f2a9ae8c start_wqthread + 0

Thread 3 name:   Dispatch queue: com.apple.root.background-qos
Thread 3:
0   libswiftCore.dylib            	       0x187dcdc60 specialized _withCocoaASCIIPointer<A>(_:requireStableAddress:work:) + 64
1   libswiftCore.dylib            	       0x187dde534 _StringObject.getSharedUTF8Start() + 36
2   libswiftCore.dylib            	       0x187dde554 _StringObject.sharedUTF8.getter + 24
3   libswiftCore.dylib            	       0x187dd25b4 _stringCompareInternal(_:_:expecting:) + 324
4   Nextcloud                     	       0x104f2a76c 0x104cf0000 + 2336620
5   Nextcloud                     	       0x104d6d98c 0x104cf0000 + 514444
6   Nextcloud                     	       0x104d6da7c 0x104cf0000 + 514684
7   CoreFoundation                	       0x18319ee18 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 24
8   CoreFoundation                	       0x1831d51c4 __NSArrayEnumerate + 456
9   Photos                        	       0x1969d26cc -[PHFetchResult enumerateObjectsUsingBlock:] + 84
10  Nextcloud                     	       0x104d6d47c 0x104cf0000 + 513148
11  Nextcloud                     	       0x104d31df8 0x104cf0000 + 269816
12  Nextcloud                     	       0x104d69d48 0x104cf0000 + 499016
13  Nextcloud                     	       0x104d6dd94 0x104cf0000 + 515476
14  Nextcloud                     	       0x104d90488 0x104cf0000 + 656520
15  libdispatch.dylib             	       0x182e9a924 _dispatch_call_block_and_release + 32
16  libdispatch.dylib             	       0x182e9c670 _dispatch_client_callout + 20
17  libdispatch.dylib             	       0x182eadf00 _dispatch_root_queue_drain + 684
18  libdispatch.dylib             	       0x182eae608 _dispatch_worker_thread2 + 164
19  libsystem_pthread.dylib       	       0x1f2a9b0b8 _pthread_wqthread + 228
20  libsystem_pthread.dylib       	       0x1f2a9ae94 start_wqthread + 8

Thread 4 name:  com.apple.uikit.eventfetch-thread
Thread 4:
0   libsystem_kernel.dylib        	       0x1b9b7e504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b9b7eb9c mach_msg + 76
2   CoreFoundation                	       0x183198738 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x18319ca2c __CFRunLoopRun + 1212
4   CoreFoundation                	       0x1831b0468 CFRunLoopRunSpecific + 600
5   Foundation                    	       0x1849cec84 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6   Foundation                    	       0x184a0fdb8 -[NSRunLoop(NSRunLoop) runUntilDate:] + 92
7   UIKitCore                     	       0x185acc74c -[UIEventFetcher threadMain] + 524
8   Foundation                    	       0x184a1e3fc __NSThread__start__ + 808
9   libsystem_pthread.dylib       	       0x1f2a9b9a4 _pthread_start + 148
10  libsystem_pthread.dylib       	       0x1f2a9aea0 thread_start + 8

Thread 5:
0   libsystem_pthread.dylib       	       0x1f2a9ae8c start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x1f2a9ae8c start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x1f2a9ae8c start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	       0x1f2a9ae8c start_wqthread + 0

Thread 9 name:  com.google.firebase.crashlytics.MachExceptionServer
Thread 9:
0   libsystem_kernel.dylib        	       0x1b9b7ff18 write + 8
1   Nextcloud                     	       0x10568e1d8 0x104cf0000 + 10084824
2   Nextcloud                     	       0x10568b080 0x104cf0000 + 10072192
3   libsystem_pthread.dylib       	       0x1f2a9b9a4 _pthread_start + 148
4   libsystem_pthread.dylib       	       0x1f2a9aea0 thread_start + 8

Thread 10 name:  com.apple.NSURLConnectionLoader
Thread 10:
0   libsystem_kernel.dylib        	       0x1b9b7e504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b9b7eb9c mach_msg + 76
2   CoreFoundation                	       0x183198738 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x18319ca2c __CFRunLoopRun + 1212
4   CoreFoundation                	       0x1831b0468 CFRunLoopRunSpecific + 600
5   CFNetwork                     	       0x183c26510 0x1839ac000 + 2598160
6   Foundation                    	       0x184a1e3fc __NSThread__start__ + 808
7   libsystem_pthread.dylib       	       0x1f2a9b9a4 _pthread_start + 148
8   libsystem_pthread.dylib       	       0x1f2a9aea0 thread_start + 8

Thread 11:
0   libsystem_pthread.dylib       	       0x1f2a9ae8c start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib       	       0x1f2a9ae8c start_wqthread + 0

Thread 13 name:  Realm notification listener
Thread 13:
0   libsystem_kernel.dylib        	       0x1b9b7fe7c kevent + 8
1   Nextcloud                     	       0x1052826a0 0x104cf0000 + 5842592
2   Nextcloud                     	       0x105283068 0x104cf0000 + 5845096
3   libsystem_pthread.dylib       	       0x1f2a9b9a4 _pthread_start + 148
4   libsystem_pthread.dylib       	       0x1f2a9aea0 thread_start + 8

Thread 14:
0   libsystem_kernel.dylib        	       0x1b9b7ef90 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1f2aa2254 _pthread_cond_wait + 1228
2   libc++.1.dylib                	       0x19bb14ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Nextcloud                     	       0x1051e8f50 0x104cf0000 + 5214032
4   Nextcloud                     	       0x1051ed464 0x104cf0000 + 5231716
5   libsystem_pthread.dylib       	       0x1f2a9b9a4 _pthread_start + 148
6   libsystem_pthread.dylib       	       0x1f2a9aea0 thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x000000016b10e6c0   x2: 0x0000000104db0db0   x3: 0x0000000280f1b250
    x4: 0x0000000000000000   x5: 0x00000001065609c0   x6: 0x0000000000000013   x7: 0x0000000000000005
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x000000040000078c  x11: 0x00ff000108816400
   x12: 0x00000000000000c2  x13: 0x0000000108817010  x14: 0x00000001062172b0  x15: 0x00000001dc5fc410
   x16: 0x0000000187f663d4  x17: 0x5262e101831b5d24  x18: 0x000000010976bedc  x19: 0x400000028073d350
   x20: 0x00000002838bc8a0  x21: 0x0000000282f88360  x22: 0x0000000280f1b240  x23: 0x4000000282f88360
   x24: 0x0000000000000000  x25: 0xc00000000000004c  x26: 0x0000000104dcd570  x27: 0x98e8734f261e90fa
   x28: 0x0000000280f1b250   fp: 0x000000016b10e730   lr: 0x7e7cd48104db0db0
    sp: 0x000000016b10e620   pc: 0x0000000104db0e6c cpsr: 0x60001000
   far: 0x000000011fe33800  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x104cf0000 -        0x1059abfff Nextcloud arm64  <27450fd551b23c2898de99e47ad67b09> /private/var/containers/Bundle/Application/7E0CAE0A-5A69-4DE5-A91E-3003CDA407A9/Nextcloud.app/Nextcloud
       0x182e98000 -        0x182edefff libdispatch.dylib arm64e  <bd02a62584753fd68dc38aed25d1573b> /usr/lib/system/libdispatch.dylib
       0x183191000 -        0x1835e4fff CoreFoundation arm64e  <e2f84645290531ef8ec73cc19c3cddb3> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
       0x19ed53000 -        0x19ed5bfff GraphicsServices arm64e  <b40e3b1790c73ebcb6bc8c7b605f47a9> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
       0x18563a000 -        0x186ec5fff UIKitCore arm64e  <920a0ee6d2663058814427a27b23ad62> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
       0x105e60000 -        0x105eb7fff dyld arm64e  <780553c7d39f322a8cb9f4f6de52610d> /usr/lib/dyld
       0x1f2a9a000 -        0x1f2aa5fff libsystem_pthread.dylib arm64e  <a17d07cfe86a392387c4921045898a8a> /usr/lib/system/libsystem_pthread.dylib
       0x187be0000 -        0x188031fff libswiftCore.dylib arm64e  <2148536d9b0c3d1d81f0ceb3009518f0> /usr/lib/swift/libswiftCore.dylib
       0x1969a6000 -        0x196c63fff Photos arm64e  <e2ea16ae84b73d43906301f112bde98a> /System/Library/Frameworks/Photos.framework/Photos
       0x1b9b7d000 -        0x1b9bb0fff libsystem_kernel.dylib arm64e  <ff3ee512a0bc3123b983d365a71fb06a> /usr/lib/system/libsystem_kernel.dylib
       0x1849b6000 -        0x184cbcfff Foundation arm64e  <925a43cdeaf2316193783ed87468301d> /System/Library/Frameworks/Foundation.framework/Foundation
       0x1839ac000 -        0x183e70fff CFNetwork arm64e  <23a465f1e97c36c5a30fcefec059f79f> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
       0x19bb0b000 -        0x19bb6efff libc++.1.dylib arm64e  <346a1fc1f0b337dbb10209951bb9aa78> /usr/lib/libc++.1.dylib

EOF
```

### Reasoning or why should it be changed/implemented?

Because crashing is bad.

### Environment data

See crash log above.

**Comment by ajay-gh** [comment]
Same problem on an iPad with iOS v12.5.5, after updating the Nextcloud app. When I try to read the version of the Nextcoud app in the iOS settings menu/dialog, the version is listed as 0 (zero). Nextcloud ran flawlessly on this iPad for years.

**Comment by thisIsTheFoxe** [comment]
@ajay-gh thanks for letting us know, but I don't think this issue is related to your problem. Please check out #1876 instead.

**Comment by thisIsTheFoxe** [comment]
@markshep Thanks for the report.
can you confirm that this issue was introduced in 4.2.1? It looks like the crash is caused by the auto-upload. Can you confirm that the auto upload is active or if the issue persists when you disable it? Also, if possible please include the app log under: More > Settings > Advanced > View Log file. And have you tried to re-install the app?

**Comment by ajay-gh** [comment]
Hi there, please read my initial post again. Unfortunately I cannot identify the app version other then saying "the latest avail. in the app store". However I can confirm that I have not / do not use the any auto upload feature, and there were no pending uploads. Finally I cannot goto the menu item you suggest because the app quits immediately, and the iOS > Settings > Nextcloud dialog does not offer access to any log. Hope this helps a little !

**Comment by markshep** [comment]
I'm not sure if this was introduced in 4.2.1 as I only just turned on auto-upload and told it to upload the existing photos from the Camera Roll.  There were just over 10,000 items to upload and it kept crashing while uploading them.  I think I must have restarted the app over 100 times while the number reduced.  The app would sometimes last quite a while and do quite a few uploads before crashing, other times it would crash instantly.  Eventually the number reduced to 134 items to upload and it's now stuck at that number and crashes before uploading any every single time.  Because it crashes so quickly I can't get to the settings to turn off auto-upload in time, neither can I get to the app log.  Is the app log saved to storage so that I could copy it off the device?

**Comment by thisIsTheFoxe** [comment]
@markshep thanks a lot for explaining. 
I'm assuming this is related to other auto-upload issues. We'll keep investigating....
The log file (named `communication.log`) is saved in the apps document directory. However, unless you mount your device directly or use some sort of backup extractor, you will probably not be able to access it. Thank you for trying, tho.

**Comment by marinofaggiana** [comment]
Soon (tomorrow?) will be available in TestFlight the version 4.2.2 Build 4, please test it if solved.

https://testflight.apple.com/join/GjNbfo2a

**Comment by markshep** [comment]
I've signed up for TestFlight, but it looks like that new version isn't uploaded yet.  I copied `communication.log` to my Mac and here are the lines from a session from start to crash: [session.txt](https://github.com/nextcloud/ios/files/8087609/session.txt)

**Comment by onkelbeh** [comment]
Just checked, no such version available, can see only 4.2.1 (7)

**Comment by marinofaggiana** [comment]
Fixed V 4.2.2 available on Apple Store

**Comment by whiskeytangofoxy** [comment]
Same issue for me on version 4.2.2 Build 7. Even uploading as few as 10 photos causes the iOS app to crash instantly. Trying to re-open the app only results in continuous crashes 1-3 seconds into app use.

**Comment by markshep** [comment]
The version on TestFlight is now 4.3.0 (1).  I installed that and it's still crashing before managing to auto-upload any files.

**Comment by whiskeytangofoxy** [comment]
I'm curious if it is some caching issue related to the HEIC-JPG conversion workflow.

**Comment by markshep** [comment]
If the .dSYM file from the build has been kept then the crash dump can be symbolicated which will show exactly which function the crash happened in.

**Comment by onkelbeh** [comment]
Yep, same here, 4.3.0 (1) crashes directly after start, IOS 12.5.5, iPhone 6.
Why can't you just publish the old version?

**Comment by markshep** [comment]
@thisIsTheFoxe - are .dSYM files kept for your released builds?
