### ISSUE TITLE
Unable to mark Favorite on folder 

### ISSUE THREAD

**Issue by janusn** [nextcloud/ios#373]
First a declaration. This is unrelated to Issue [#223](https://github.com/nextcloud/ios/issues/223) as it does not involve LDAP.

**Steps to reproduce:**
1. tap on the "Files" shortcut on the bottom dock
2. slide a folder to right to reveal "Favorite" widget
3. tap on the "Favorite" widget
4. tap on the "Favorites" shortcut on the bottom dock

**Expected result:**
The newly favorited folder appears.

**Actual result:**
The newly favorited folder does not appear.

**Environment:**
Nextcloud client version: 2.17.8.00002
iOS version: 10.3.3 (15G60)
Nextcloud server version: 10.0.6
Authentication: the oc_users table in the database.

**Comment by marinofaggiana** [comment]
@MorrisJobke please, if possible, try with next beta TestFlight 2.18.0 Build 5 for LDAP search, favourites, set YES/NO favorite

thanks

**Comment by marinofaggiana** [comment]
@MorrisJobke ping thanks

**Comment by janusn** [comment]
The version reported in the app is "Nextcloud for iOS 2.19.1.00002 @2017 T.W.S. Inc.Nextcloud Server 10.0.6". This bug still have not been fixed.

By the way, I have discovered that, favorite status set in the Web interface shows up on the iOS app but the files inside the favorited folder are not downloaded even the "Favorites available offline" option is set.

**Comment by iHell** [comment]
@marinofaggiana 
Unfortunately this didn't solve the bug. It's still present and kind of annoying regarding offline files.
Would love to see a fix for it.
I know changing the LDAP Mapping Attribute in the Expert Tab to AD mail/sAMAccountName is a workaround, but then I have to login with the chosen attribute either.

**Comment by marinofaggiana** [comment]
@iHell can you make a account test for me with this issue ?

**Comment by iHell** [comment]
Okay, this is kind of weird. I've made a fresh install of Nextcloud 13 a few days ago. Then I've logged in to the Nextcloud App on iOS and had this Issue again.
Today I've retried it and everything suddenly worked fine. I've tried to reproduce it, but it worked in every folder.
Then I've completely wiped the Account out of the App (More->Settings->Advanced->End) and logged back in. And now the issue is back.
Is it possible that this issue is present only for some time after log in to the App?

@marinofaggiana I've created a test account for you and will send you the credentials and server address to ios @ nextcloud dot com.

**Comment by marinofaggiana** [comment]
@iHell do u have a Testflight  account ?

**Comment by iHell** [comment]
@marinofaggiana 
Thanks for resolving this Issue!
I've no TestFlight Account yet. If you're able to send me an invitation, my Apple-ID is the E-mail Address, from which I've sent you the test account.

**Comment by marinofaggiana** [comment]
ok done. please try. thx

**Comment by iHell** [comment]
Tested the Testflight version. Issue is fixed in my environment.
Thanks @marinofaggiana

**Comment by janusn** [comment]
I have just updated the iOS version to 2.20.4.00005 on both iPad and iPhone.
The favorite is still not marked by sliding to right on folders but it works on individual files.

Sliding on a folder does trigger it downloads the files inside though.

Marking favorite on web portal does work and favored folders does appear in the iOS version.

**Comment by marinofaggiana** [comment]
mmm @janusn can you create a account test for me with a folder that do not mark as favorite ?

**Comment by marinofaggiana** [comment]
@janusn ios at nextcloud dot com

**Comment by janusn** [comment]
Thanks for helping. Credential sent.

**Comment by marinofaggiana** [comment]
@janusn before update your server to Nextcloud 13 !! you have the Nextcloud 10.0.6. 

Close.

**Comment by janusn** [comment]
I am stuck with Nextcloud Server 10.0.6 due to the nextcloud plugin of FreeNAS. :(
