### ISSUE TITLE
Videos not auto uploading

### ISSUE THREAD

**Issue by kman1898** [nextcloud/ios#3857]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Enable auto upload for pictures and videos.
2. Capture several photos and videos using the iOS device.
3. Check the upload destination folder on the server.

### Expected behaviour
All photos and videos should upload automatically to the configured folder.

### Actual behaviour
Photos upload correctly. Videos do not upload at all.

### Reasoning or why should it be changed/implemented?
Videos should upload along with photos to ensure complete media backup functionality.

### Environment data

iOS version: iOS 26.0.1

Nextcloud iOS app version: 7.1.8.11

Server operating system: Unraid 7.1.4

Web server: Nextcloud AIO (11.10.0)

Database: Included with Nextcloud AIO

PHP version: Included with Nextcloud AIO

Nextcloud version: 31.0.10

**Comment by marinofaggiana** [comment]
@kman1898 can you try the TestFlight version ?

**Comment by coolapso** [comment]
> [@kman1898](https://github.com/kman1898) can you try the TestFlight version ?

while i'm not the reporter, I have the same issue. Installed the test flight version and same problem. ~However .. I noticed that some videos get uploaded and other are not. seems to be a "intermittent" issue. not uploaded videos are not retried at all as if nextcloud either is ignoring them or "thinks" they are already synced.~

edit: scratch that part .. what I thought to be videos, are the "live photos" 

edit2: I have noticed that this happened only when nextcloud auto uploaded when I was outside, using networks that I usually don't use, wonder if this could be related. When I made the sync both Wi-fi and mobile networks were flaky and often slow. I don't have the "enable background location" active, also I don't have nextcloud setup to "only use wi-fi connection".

**Comment by Whatnoww** [comment]
Same issue here, photos will auto upload, but videos don’t unless I’ve opened the app shortly after taking the video. I’m also on the test flight.

**Comment by thomasmerz** [comment]
@marinofaggiana I have the same problem - but much with much more current version than mentioned here:

Nextcloud Hub 26 Spring (34.0.1)
Nextcloud Matheria for iOS 33.0.10.2

Error message in App:
> Create folder error

Photos can be auto-uploaded in the same folder, that can't be created (because it already exists!)… 🤔 Should I open a new ticket for this or do you need more infos? I think that version 33.0.9 was working fine before. Videos I want to upload are from Jun 27th. Usually I don't upload videos on a daily basis; so I assume before this date/version it worked fine. So 33.0.10 might have broken something… 🤷🏼‍♂️

**Comment by marinofaggiana** [comment]
Is fixed with the last 33.1.x ?

**Comment by thomasmerz** [comment]
Got an Update yesterday:

Nextcloud Matheria for iOS 33.1.1.2 © 2026

Nextcloud Server 34.0.1

But Videos still won't be uploaded with "create folder error" while Photos will still be uploaded. 🥺

**Comment by thomasmerz** [comment]
Update from my side:  

new/current videos could be uploaded (automatically) - but older ones still won't be automatically or even manually be uploaded… So, for new videos this seems fixed ❤️  

But how do I got my old videos uploaded if even manual uploading is failing? 🤷🏼‍♂️
