### ISSUE TITLE
Adjust action buttons to iOS standard 

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/ios#433]
![da4e7a4f-d159-4402-bb4c-e3fa27f3254b](https://user-images.githubusercontent.com/19711361/34154662-97914ee0-e4b6-11e7-9f22-b0a789364119.jpeg)
![ed95aaa4-b33d-495b-8aa3-0a325b6ddbb7](https://user-images.githubusercontent.com/19711361/34154663-97bfb794-e4b6-11e7-9a7d-8833114a3348.jpeg)

**Comment by marinofaggiana** [comment]
@jancborchardt what do you think ?

**Comment by jancborchardt** [comment]
Yup, absolutely agree! :) We should use the standards wherever possible.

**Comment by marinofaggiana** [comment]
ok

**Comment by jancborchardt** [comment]
Just instead of the flag icon, we should use the favorite star, right? :)

**Comment by marinofaggiana** [comment]
No, favorite is on Left ..

**Comment by marinofaggiana** [comment]
![schermata 2017-12-20 alle 12 49 42](https://user-images.githubusercontent.com/8616947/34205835-43d8a626-e584-11e7-8859-3bd0d09a6cd5.png)
![schermata 2017-12-20 alle 12 49 28](https://user-images.githubusercontent.com/8616947/34205837-456cd93a-e584-11e7-9f5a-56aa860cb9b4.png)

**Comment by marinofaggiana** [comment]
Fixed on 2.19.1

**Comment by jancborchardt** [comment]
Can we also use the default iOS delete icon, the filled one?

**Comment by rakekniven** [comment]
Still have an issue with it and support @jancborchardt comment:

> Just instead of the flag icon, we should use the favorite star, right? :)

iOS mail app:
![2018-01-05 18-34-150521](https://user-images.githubusercontent.com/2069590/34730283-3716a7ae-f55f-11e7-9ad2-48700ea31573.png)

Right swipe on nextcloud app:
![2018-01-05 18-35-010522](https://user-images.githubusercontent.com/2069590/34730301-48698e22-f55f-11e7-9de0-b22f4319b3e0.png)

Left swipe:
![2018-01-05 18-35-250523](https://user-images.githubusercontent.com/2069590/34730317-522d3d50-f55f-11e7-93a9-5fa1927c6bad.png)

**Comment by jancborchardt** [comment]
Yeah, let's make sure the colors are proper. :) @marinofaggiana simply use the ones like from mail. Except for the star of course, there a bit darker yellow would be nice (is there another Apple app which uses star yellow?)

**Comment by MariusBluem** [comment]
Notes:

![33284ea4-ee23-4ef0-9f24-4580f0af7b07](https://user-images.githubusercontent.com/19711361/34744190-a4b8fb7c-f58c-11e7-83b0-b1a902b1b72c.jpeg)
![1afbd3f2-bbb0-42f6-b0ab-8034b797bc98](https://user-images.githubusercontent.com/19711361/34744191-a4dcbb98-f58c-11e7-8395-0d57846e3716.jpeg)

**Comment by jancborchardt** [comment]
@marinofaggiana take the delete and more-grey colors from the Mail app. And the background color for the star should be #ffcc00, like the color of our star.

**Comment by rakekniven** [comment]
Hello @marinofaggiana will you adjust this for next release. I will happily test it and provide feedback.

**Comment by rakekniven** [comment]
IMHO this is still open. Just checked with v2.20.3 Testflight and colors are still different.

Will remove milestone.

@marinofaggiana Any update from your side?
